name: "Check Clang Format"

on: [push, pull_request]

jobs:
  format:
    name: "Check Clang Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt update -y
          sudo apt install -y clang-format
      - name: Format Codes
        run: clang-format -i main.cpp
      - name: Check diff
        run: git diff --exit-code HEAD
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "style: Format codes"
          title: "Format codes for ${{ github.ref }}"
          labels: "style"
          assignees: "${{ github.actor }}"
          reviewers: "${{ github.actor }}"
          branch: "auto-pr/clang-format/${{ github.ref }}"
