name: "Update AUR"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"

env:
  PKGNAME: noi-despised-git

jobs:
  aur:
    name: "Update AUR"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ouuan'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")"

      - name: Update PKGBUILD
        run: sed -i "s/@VERSION@/${{ steps.get-version.outputs.version }}/" aur/PKGBUILD

      - name: Check PKGBUILD
        uses: ouuan/pkgbuild-action@master
        with:
          path: aur

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: ${{ env.PKGNAME }}
          pkgbuild: aur/PKGBUILD
          commit_username: Yufan You
          commit_email: ouuansteve@gmail.com
          commit_message: "Update from GitHub Actions: ${{ steps.get-version.outputs.version }}\n\nhttps://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
